<?php

declare(strict_types=1);

return [
    ['GET', '/', 'HomeController@index'],

    ['GET', '/front/company', 'SnapshotController@show'],
    ['GET', '/front/company/company1', 'SnapshotController@show'],
    ['GET', '/front/company/company2', 'SnapshotController@show'],
    ['GET', '/front/company/company3', 'SnapshotController@show'],
    ['GET', '/front/company/company4', 'SnapshotController@show'],
    ['GET', '/front/company/privacy', 'SnapshotController@show'],
    ['GET', '/front/company/term', 'SnapshotController@show'],
    ['GET', '/front/community', 'SnapshotController@show'],
    ['GET', '/front/community/gongsabi', 'SnapshotController@show'],
    ['GET', '/front/community/market', 'SnapshotController@show'],
    ['GET', '/front/community/partners', 'SnapshotController@show'],
    ['GET', '/front/community/recruit', 'SnapshotController@show'],
    ['GET', '/front/customer', 'SnapshotController@show'],
    ['GET', '/front/customer/notice', 'SnapshotController@show'],
    ['GET', '/front/customer/notice_view/21', 'SnapshotController@show'],
    ['GET', '/front/customer/notice_view/22', 'SnapshotController@show'],
    ['GET', '/front/customer/notice_view/23', 'SnapshotController@show'],
    ['GET', '/front/customer/notice_view/27', 'SnapshotController@show'],
    ['GET', '/front/customer/pds', 'SnapshotController@show'],
    ['GET', '/front/customer/faq', 'SnapshotController@show'],
    ['GET', '/front/customer/qna', 'SnapshotController@show'],
    ['GET', '/front/data', 'SnapshotController@show'],
    ['GET', '/front/data/gongsabi', 'SnapshotController@show'],
    ['GET', '/front/data/danga', 'SnapshotController@show'],
    ['GET', '/front/data/goljo', 'SnapshotController@show'],
    ['GET', '/front/education', 'SnapshotController@show'],
    ['GET', '/front/education/youtube', 'SnapshotController@show'],
    ['GET', '/front/education/book', 'SnapshotController@show'],
    ['GET', '/front/education/lecture', 'SnapshotController@show'],
    ['GET', '/front/education/lecture_regist', 'SnapshotController@show'],
    ['GET', '/front/report', 'SnapshotController@show'],
    ['GET', '/front/report/geonchuk', 'SnapshotController@show'],
    ['GET', '/front/report/goljo', 'SnapshotController@show'],
    ['GET', '/front/report/gigan', 'SnapshotController@show'],
    ['GET', '/front/report/ganjeob', 'SnapshotController@show'],

    ['GET', '/front/company', 'PageController@company'],
    ['GET', '/front/company/company1', 'PageController@company'],
    ['GET', '/front/company/company2', 'PageController@company'],
    ['GET', '/front/company/company3', 'PageController@company'],
    ['GET', '/front/company/company4', 'PageController@company'],
    ['GET', '/front/company/privacy', 'PageController@privacy'],
    ['GET', '/front/company/term', 'PageController@terms'],

    ['GET', '/front/community', 'PageController@community'],
    ['GET', '/front/community/gongsabi', 'PageController@community'],
    ['GET', '/front/community/market', 'PageController@community'],
    ['GET', '/front/community/partners', 'PageController@community'],
    ['GET', '/front/community/recruit', 'PageController@community'],

    ['GET', '/front/auth/login', 'AuthController@loginForm'],
    ['POST', '/front/auth/login', 'AuthController@login'],
    ['GET', '/front/auth/regist', 'AuthController@registerForm'],
    ['POST', '/front/auth/regist', 'AuthController@register'],
    ['POST', '/front/auth/logout', 'AuthController@logout'],

    ['GET', '/front/customer', 'CustomerController@notice'],
    ['GET', '/front/customer/notice', 'CustomerController@notice'],
    ['GET', '/front/customer/notice_view/{id}', 'CustomerController@show'],
    ['GET', '/front/customer/pds', 'CustomerController@pds'],
    ['GET', '/front/customer/faq', 'CustomerController@faq'],
    ['GET', '/front/customer/qna', 'CustomerController@qnaForm'],
    ['POST', '/front/customer/qna', 'CustomerController@qnaStore'],
    ['GET', '/front/customer/contact', 'PageController@contact'],

    ['GET', '/front/report', 'ReportController@index'],
    ['GET', '/front/report/geonchuk', 'ReportController@form'],
    ['GET', '/front/report/goljo', 'ReportController@form'],
    ['GET', '/front/report/gigan', 'ReportController@form'],
    ['GET', '/front/report/ganjeob', 'ReportController@form'],
    ['POST', '/front/report/estimate', 'ReportController@estimate'],

    ['GET', '/front/data', 'DataController@index'],
    ['GET', '/front/data/gongsabi', 'DataController@index'],
    ['GET', '/front/data/goljo', 'DataController@index'],
    ['GET', '/front/data/danga', 'DataController@index'],

    ['GET', '/front/education', 'EducationController@index'],
    ['GET', '/front/education/lecture', 'EducationController@lecture'],
    ['GET', '/front/education/book', 'EducationController@book'],
    ['GET', '/front/education/youtube', 'EducationController@youtube'],
    ['GET', '/front/education/lecture_regist', 'EducationController@lectureRegister'],

    ['POST', '/front/payment/prepare', 'PaymentController@prepare'],
    ['POST', '/front/payment/complete', 'PaymentController@complete'],

    ['GET', '/front/mypage/info/info2', 'AuthController@mypage'],

    ['GET', '/admin', 'AdminController@dashboard'],
    ['GET', '/admin/settings', 'AdminController@settings'],
    ['POST', '/admin/settings', 'AdminController@saveSettings'],
];
